create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null check (role in ('student', 'teacher')),
  age integer,
  level text,
  state text,
  lga text,
  school text,
  approved boolean not null default false,
  teacher_id uuid references public.profiles(id) on delete set null,
  teacher_email text,
  progress jsonb not null default '{}'::jsonb,
  questions_asked integer not null default 0,
  last_active bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.private_data (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  data jsonb not null default '{}'::jsonb
);

alter table public.profiles add column if not exists teacher_email text;

create table if not exists public.login_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('student', 'teacher')),
  created_at bigint not null
);

create table if not exists public.student_access_codes (
  id text primary key,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  code text not null unique,
  state text not null,
  lga text not null,
  school text not null,
  created_at bigint not null
);

create table if not exists public.inbox_messages (
  id text primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  sender_role text not null check (sender_role in ('student', 'teacher')),
  sender_name text not null,
  message text not null,
  created_at bigint not null
);

create table if not exists public.teacher_questions (
  id text primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_email text not null,
  student_name text not null,
  question text not null,
  asked_at bigint not null,
  answered boolean not null default false,
  answer text,
  answered_at bigint
);

create table if not exists public.assignments (
  id text primary key,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  question text not null,
  due_date text,
  created_at bigint not null,
  answer text not null default '',
  submitted_at bigint,
  score numeric,
  feedback text not null default '',
  marked_at bigint,
  notification_seen boolean not null default false
);

create index if not exists profiles_teacher_id_idx on public.profiles(teacher_id);
create index if not exists inbox_messages_participants_idx on public.inbox_messages(student_id, teacher_id, created_at);
create index if not exists teacher_questions_participants_idx on public.teacher_questions(student_id, teacher_id, asked_at);
create index if not exists assignments_participants_idx on public.assignments(student_id, teacher_id, created_at);

create or replace function public.validate_student_code(
  p_code text,
  p_state text,
  p_lga text,
  p_school text
) returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.student_access_codes c
    where upper(trim(c.code)) = upper(trim(p_code))
      and lower(regexp_replace(trim(c.state), '\s+', ' ', 'g')) = lower(regexp_replace(trim(p_state), '\s+', ' ', 'g'))
      and lower(regexp_replace(trim(c.lga), '\s+', ' ', 'g')) = lower(regexp_replace(trim(p_lga), '\s+', ' ', 'g'))
      and lower(regexp_replace(trim(c.school), '\s+', ' ', 'g')) = lower(regexp_replace(trim(p_school), '\s+', ' ', 'g'))
  );
$$;

create or replace function public.create_profile_for_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_role text := coalesce(new.raw_user_meta_data->>'role', 'student');
  v_teacher_id uuid;
  v_teacher_email text;
  v_state text := coalesce(new.raw_user_meta_data->>'state', '');
  v_code text := coalesce(new.raw_user_meta_data->>'access_code', '');
  v_expected_teacher_code text;
begin
  if v_role not in ('student', 'teacher') then
    raise exception 'Invalid account role';
  end if;

  if v_role = 'teacher' then
    if upper(v_state) like '%ABUJA%' or upper(v_state) like '%FEDERAL CAPITAL%' or upper(v_state) = 'FCT' then
      v_expected_teacher_code := 'ABUJA-TEACH';
    else
      v_expected_teacher_code := upper(regexp_replace(v_state, '[^A-Za-z]', '', 'g')) || '-TEACH';
    end if;
    if upper(v_code) <> v_expected_teacher_code then
      raise exception 'Invalid teacher registration code';
    end if;
  else
    select c.teacher_id, p.email into v_teacher_id, v_teacher_email
    from public.student_access_codes c
    join public.profiles p on p.id = c.teacher_id
    where upper(trim(c.code)) = upper(trim(v_code))
      and lower(regexp_replace(trim(c.state), '\s+', ' ', 'g')) = lower(regexp_replace(trim(coalesce(new.raw_user_meta_data->>'state','')), '\s+', ' ', 'g'))
      and lower(regexp_replace(trim(c.lga), '\s+', ' ', 'g')) = lower(regexp_replace(trim(coalesce(new.raw_user_meta_data->>'lga','')), '\s+', ' ', 'g'))
      and lower(regexp_replace(trim(c.school), '\s+', ' ', 'g')) = lower(regexp_replace(trim(coalesce(new.raw_user_meta_data->>'school','')), '\s+', ' ', 'g'))
    limit 1;
    if v_teacher_id is null then
      raise exception 'Invalid student access code or school details';
    end if;
  end if;

  insert into public.profiles(id, email, name, role, age, level, state, lga, school, approved, teacher_id, teacher_email, last_active)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    v_role,
    nullif(new.raw_user_meta_data->>'age', '')::integer,
    nullif(new.raw_user_meta_data->>'level', ''),
    nullif(new.raw_user_meta_data->>'state', ''),
    nullif(new.raw_user_meta_data->>'lga', ''),
    nullif(new.raw_user_meta_data->>'school', ''),
    v_role = 'teacher' or v_teacher_id is not null,
    v_teacher_id,
    v_teacher_email,
    (extract(epoch from now()) * 1000)::bigint
  );
  insert into public.private_data(user_id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_codestart on auth.users;
create trigger on_auth_user_created_codestart
  after insert on auth.users
  for each row execute procedure public.create_profile_for_new_auth_user();

create or replace function public.prevent_profile_privilege_changes()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if auth.uid() = old.id and (new.role <> old.role or new.teacher_id is distinct from old.teacher_id or new.approved is distinct from old.approved or new.email <> old.email) then
    raise exception 'Account role and teacher approval cannot be changed by the account owner';
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_profile_privilege_changes on public.profiles;
create trigger prevent_profile_privilege_changes
  before update on public.profiles
  for each row execute procedure public.prevent_profile_privilege_changes();

create or replace function public.guard_assignment_updates()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if auth.uid() = old.student_id then
    if new.teacher_id <> old.teacher_id or new.student_id <> old.student_id or new.title <> old.title or new.question <> old.question or new.score is distinct from old.score or new.feedback <> old.feedback or new.marked_at is distinct from old.marked_at then
      raise exception 'Students may only submit an assignment answer';
    end if;
  elsif auth.uid() = old.teacher_id then
    if new.teacher_id <> old.teacher_id or new.student_id <> old.student_id or new.title <> old.title or new.question <> old.question or new.answer <> old.answer or new.submitted_at is distinct from old.submitted_at then
      raise exception 'Teachers may only mark submitted work';
    end if;
  else
    raise exception 'Not an assignment participant';
  end if;
  return new;
end;
$$;

drop trigger if exists guard_assignment_updates on public.assignments;
create trigger guard_assignment_updates
  before update on public.assignments
  for each row execute procedure public.guard_assignment_updates();

alter table public.profiles enable row level security;
alter table public.private_data enable row level security;
alter table public.student_access_codes enable row level security;
alter table public.inbox_messages enable row level security;
alter table public.teacher_questions enable row level security;
alter table public.assignments enable row level security;
alter table public.login_sessions enable row level security;

drop policy if exists "profiles self and linked students" on public.profiles;
create policy "profiles self and linked students" on public.profiles
  for select to authenticated using (id = auth.uid() or teacher_id = auth.uid());
drop policy if exists "profile owner update" on public.profiles;
create policy "profile owner update" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "private data owner only" on public.private_data;
create policy "private data owner only" on public.private_data
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "teacher manages own access codes" on public.student_access_codes;
create policy "teacher manages own access codes" on public.student_access_codes
  for all to authenticated using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());

drop policy if exists "participants read inbox messages" on public.inbox_messages;
create policy "participants read inbox messages" on public.inbox_messages
  for select to authenticated using (student_id = auth.uid() or teacher_id = auth.uid());
drop policy if exists "linked participants send inbox messages" on public.inbox_messages;
create policy "linked participants send inbox messages" on public.inbox_messages
  for insert to authenticated with check (
    sender_id = auth.uid() and (
      (sender_role = 'student' and student_id = auth.uid() and exists(select 1 from public.profiles p where p.id = student_id and p.teacher_id = teacher_id))
      or (sender_role = 'teacher' and teacher_id = auth.uid() and exists(select 1 from public.profiles p where p.id = student_id and p.teacher_id = auth.uid()))
    )
  );

drop policy if exists "participants read teacher questions" on public.teacher_questions;
create policy "participants read teacher questions" on public.teacher_questions
  for select to authenticated using (student_id = auth.uid() or teacher_id = auth.uid());
drop policy if exists "student sends teacher questions" on public.teacher_questions;
create policy "student sends teacher questions" on public.teacher_questions
  for insert to authenticated with check (student_id = auth.uid() and exists(select 1 from public.profiles p where p.id = student_id and p.teacher_id = teacher_id));
drop policy if exists "teacher answers linked questions" on public.teacher_questions;
create policy "teacher answers linked questions" on public.teacher_questions
  for update to authenticated using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());

drop policy if exists "participants read assignments" on public.assignments;
create policy "participants read assignments" on public.assignments
  for select to authenticated using (student_id = auth.uid() or teacher_id = auth.uid());
drop policy if exists "teacher assigns linked students" on public.assignments;
create policy "teacher assigns linked students" on public.assignments
  for insert to authenticated with check (teacher_id = auth.uid() and exists(select 1 from public.profiles p where p.id = student_id and p.teacher_id = auth.uid()));
drop policy if exists "participants update assignment fields" on public.assignments;
create policy "participants update assignment fields" on public.assignments
  for update to authenticated using (student_id = auth.uid() or teacher_id = auth.uid()) with check (student_id = auth.uid() or teacher_id = auth.uid());

grant select, update on public.profiles to authenticated;
grant select, insert, update on public.private_data to authenticated;
grant select, insert, update, delete on public.student_access_codes to authenticated;
grant select, insert on public.inbox_messages to authenticated;
grant select, insert, update on public.teacher_questions to authenticated;
grant select, insert, update on public.assignments to authenticated;
grant select, insert on public.login_sessions to authenticated;
grant execute on function public.validate_student_code(text, text, text, text) to anon, authenticated;

drop policy if exists "users manage own login sessions" on public.login_sessions;
create policy "users manage own login sessions" on public.login_sessions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());